const express = require('express')
const route = express.Router()
const {DataEntry, FolioEntry, FolioUpdate, getEnquiry, getFolio, SupplierEntry, SupplierEntryDetails, FolioArrayUpdate, getDataBetweenDates, SupplierArrayUpdate} = require('../Controllers/MainController')
route.post('/enquiryentry',DataEntry)
route.post('/Folioentry',FolioEntry)
route.post('/updateFolioentry',FolioUpdate)
route.post('/Supplierentry',SupplierEntry)
route.get('/getEnquiry',getEnquiry)
route.get('/getFolio',getFolio)
route.post('/getSupplierDetails',getDataBetweenDates)
route.post('/Folioupdate/:id',FolioArrayUpdate)
route.post('/Supplierupdate/:id',SupplierArrayUpdate)
module.exports = route